window.AUGMENT_POOL = [
  "3 Threes",
  "A Magic Roll",
  "Advanced Loan",
  "Advanced Loan+",
  "Air Axiom",
  "Arcane Viktor-y",
  "Artillery Barrage",
  "Ascension",
  "Augmented Power",
  "Aura Farming",
  "Backup Bows",
  "Band of Thieves",
  "Band of Thieves II",
  "Band of Thieves II+",
  "Band of Thieves II++",
  "Bandle Bounty I",
  "Bandle Bounty II",
  "Belt Overflow",
  "Best Friends I",
  "Best Friends II",
  "Big Friend I",
  "Big Grab Bag",
  "Big Spender",
  "Binary Airdrop",
  "Birthday Present",
  "Birthday Reunion",
  "Blood Offering",
  "Bodyguard Training",
  "Boxing Lessons",
  "Branching Out",
  "Branching Out+",
  "Bringer of Ruin",
  "Bronze For Life I",
  "Bronze For Life II",
  "Buried Treasures",
  "Calculated Loss",
  "Call to Chaos",
  "Called Shot",
  "Care Package",
  "Caretaker's Ally",
  "Caretaker's Favor",
  "Carve a Path",
  "Celestial Blessing I",
  "Celestial Blessing II",
  "Celestial Blessing III",
  "Chaos Magic",
  "Chaotic Evolution",
  "Chosen Wolves",
  "Clear Mind",
  "Clockwork Accelerator",
  "Cluttered Mind",
  "Comeback Story",
  "Commerce Core",
  "Component Buffet",
  "Component Heist",
  "Construct a Companion",
  "Continuous Conjuration",
  "Cooking Pot",
  "Coronation",
  "Corrosion",
  "Cosmic Calling",
  "Crafted Crafting",
  "Crash Test Dummies",
  "Critical Success",
  "Crown's Will",
  "Cry Me A River",
  "Cursed Crown",
  "Deadlier Blades",
  "Deadlier Caps",
  "Defense of the Placidium",
  "Delayed Start",
  "Demacia Forever",
  "Double Trouble",
  "Dragonguards",
  "Dummify",
  "Duo Queue",
  "Early Education",
  "Early Learnings",
  "Earth Axiom",
  "Efficient Shopper",
  "Epic Rolldown",
  "Epoch",
  "Epoch+",
  "Evolve and Overcome",
  "Exclusive Customization",
  "Exiles I",
  "Exiles II",
  "Expected Unexpectedness",
  "Explosive Growth",
  "Explosive Growth+",
  "Extra Buckles",
  "Eye For An Eye",
  "Eye For An Eye+",
  "Feed the Flames",
  "Find Your Center",
  "Fire Axiom",
  "Firesale",
  "Flexible",
  "Flowing Tears",
  "Focused Fire",
  "Forged in Strength",
  "Forward Thinking",
  "Four Score",
  "Gain 21 Gold",
  "Giant and Mighty",
  "Gilded Steel",
  "Glass Cannon I",
  "Glass Cannon II",
  "Going Long",
  "Gold Destiny",
  "Gold Destiny+",
  "Golemify",
  "Good For Something I",
  "Growth Mindset",
  "Hard Bargain",
  "Hard Commit",
  "Healing Orbs I",
  "Healing Orbs II",
  "Heart of Steel",
  "Heavy Is the Crown",
  "Hedge Fund",
  "Hefty Rolls",
  "Heroic Grab Bag",
  "Heroic Grab Bag+",
  "Heroic Grab Bag++",
  "High Voltage",
  "Hold the Line",
  "Hustler",
  "Indecision I",
  "Indecision II",
  "Indiscriminate Killer",
  "Infinity Protection",
  "Invested+",
  "Invested++",
  "Iron Assets",
  "Item Grab Bag",
  "Ixtal Expeditionist",
  "Jeweled Lotus I",
  "Jeweled Lotus II",
  "Just Hit",
  "Kahunahuna",
  "Know Your Enemy",
  "Last Second Save",
  "Late Game Scaling",
  "Late Game Specialist",
  "Latent Forge",
  "Leap of Faith",
  "Legion of Threes",
  "Level Up!",
  "Lifting Competition",
  "Lineup",
  "Little Buddies",
  "Living Forge",
  "Lucky Gloves",
  "Lucky Gloves+",
  "Lunch Money",
  "Luxury Subscription",
  "Mace's Will",
  "Makeshift Armor I",
  "Makeshift Armor II",
  "Malicious Monetization",
  "Max Build",
  "Mess Hall",
  "Min-Max",
  "Missed Connections",
  "Money Monsoon",
  "NO SCOUT NO PIVOT",
  "Nine Lives",
  "On a Roll",
  "One Buff, Two Buff",
  "One Twos Three",
  "One, Two, Five!",
  "Over Encumbered",
  "Pandora's Bench",
  "Pandora's Items",
  "Pandora's Items II",
  "Pandora's Items III",
  "Patience is a Virtue",
  "Patient Study",
  "Pilfer",
  "Placebo",
  "Placebo+",
  "Plot Armor",
  "Portable Forge",
  "Precision and Grace",
  "Preparation I",
  "Preparation II",
  "Prismatic Destiny",
  "Prismatic Destiny+",
  "Prismatic Ticket",
  "Prizefighter",
  "Promised Protection",
  "Pyromaniac",
  "Radiant Rascal",
  "Radiant Relics",
  "Raining Gold",
  "Recombobulator",
  "ReinFOURcement",
  "Replication",
  "Restart Mission",
  "Retribution",
  "Risky Moves",
  "Rolling For Days I",
  "Salvage Bin",
  "Salvage Bin+",
  "Savings Account",
  "Second Wind",
  "Second Wind II",
  "Secrets of the Sands",
  "Sentinels of Light",
  "Shimmerscale Essence",
  "Shopping Spree",
  "Silco's Revenge",
  "Silver Destiny",
  "Silver Destiny+",
  "Silver Spoon",
  "Slammin'",
  "Slammin'+",
  "Slice of Life",
  "Slightly Magic Roll",
  "Small Grab Bag",
  "Solo Leveling",
  "Solo Plate",
  "Soul Awakening",
  "Spear's Will",
  "Speedy Double Kill",
  "Spirit Link",
  "Spirit of Redemption",
  "Spoils of War I",
  "Spoils of War II",
  "Spoils of War III",
  "Spreading Roots",
  "Spreading Roots+",
  "Staffsmith",
  "Stand United",
  "Stars Are Born",
  "Starter Kit",
  "Survivor",
  "Sweet Treats",
  "Sword Overflow",
  "Swordsmith",
  "Table Scraps",
  "Tactician's Kitchen",
  "Team Building",
  "Teaming Up",
  "The Golden Dragon",
  "The Golden Egg",
  "The Ruined King",
  "The Trait Tree",
  "The Trait Tree+",
  "The World Runes",
  "Thorn-Plated Armor",
  "Timewinders",
  "Tiniest Titan",
  "Tiny, but Deadly",
  "Titanic Titan",
  "Tons of Stats!",
  "Trade Sector",
  "Treasure Hunt",
  "Trials of Twilight",
  "Trials of Twilight II",
  "Trifecta I",
  "Trifecta II",
  "Twin Guardians",
  "Two Much Value",
  "Two Trick",
  "Unsealed From Steel",
  "Upward Mobility",
  "Urf's Gambit",
  "Walk The True Path I",
  "Walk The True Path II",
  "Wand Overflow",
  "Warlord's Honor",
  "Warpath",
  "Water Axiom",
  "We Stick Together",
  "Wild Growth",
  "Win Out",
  "Worth the Wait",
  "Worth the Wait II",
  "Woven Magic"
];
