window.ITEM_POOL = [
  "Adaptive Helm",
  "Aegis of Dawn",
  "Aegis of Dusk",
  "Arcanist Emblem",
  "Archangel's Staff",
  "B.F. Sword",
  "Barknuckles",
  "Bilgewater Emblem",
  "Blackmarket Explosives",
  "Blighting Jewel",
  "Bloodthirster",
  "Blue Buff",
  "Bramble Vest",
  "Bruiser Emblem",
  "Cappa Juice",
  "Captain's Brew",
  "Captain's Hat",
  "Chain Vest",
  "Crown of Demacia",
  "Crownguard",
  "Cutthroat's Cutlass",
  "Dawncore",
  "Dead Man's Dagger",
  "Death's Defiance",
  "Deathblade",
  "Deathfire Grasp",
  "Defender Emblem",
  "Demacia Emblem",
  "Disruptor Emblem",
  "Dragon's Claw",
  "Dreadway Cannon",
  "Edge of Night",
  "Eternal Pact",
  "Evenshroud",
  "First Mate's Flintlock",
  "Fishbones",
  "Flickerblade",
  "Freljord Emblem",
  "Frying Pan",
  "Gambler's Blade",
  "Gargoyle Stoneplate",
  "Giant Slayer",
  "Giant's Belt",
  "Gold Collector",
  "Guinsoo's Rageblade",
  "Gunslinger Emblem",
  "Hand of Justice",
  "Haunted Spyglass",
  "Hellfire Hatchet",
  "Hextech Gunblade",
  "Horizon Focus",
  "Hullcrusher",
  "Indomitable Gauntlet",
  "Infinity Edge",
  "Infinity Force",
  "Innervating Locket",
  "Invoker Emblem",
  "Ionia Emblem",
  "Ionic Spark",
  "Ixtal Emblem",
  "Jeweled Gauntlet",
  "Juggernaut Emblem",
  "Kraken's Fury",
  "Last Whisper",
  "Lesser Mirrored Persona",
  "Lich Bane",
  "Lightshield Crest",
  "Longshot Emblem",
  "Lucky Doubloon",
  "Manazane",
  "Mending Echoes",
  "Mirrored Persona",
  "Mittens",
  "Mogul's Mail",
  "Morellonomicon",
  "Needlessly Large Rod",
  "Negatron Cloak",
  "Noxus Emblem",
  "Pile O' Citrus",
  "Piltover Emblem",
  "Protector's Vow",
  "Quicksilver",
  "Quickstriker Emblem",
  "Rabadon's Deathcap",
  "Radiant Archangel's Staff",
  "Radiant Bloodthirster",
  "Radiant Blue Buff",
  "Radiant Bramble Vest",
  "Radiant Crownguard",
  "Radiant Deathblade",
  "Radiant Dragon's Claw",
  "Radiant Edge of Night",
  "Radiant Evenshroud",
  "Radiant Gargoyle's Stoneplate",
  "Radiant Giant Slayer",
  "Radiant Guinsoo's Rageblade",
  "Radiant Hand of Justice",
  "Radiant Hextech Gunblade",
  "Radiant Infinity Edge",
  "Radiant Ionic Spark",
  "Radiant Jeweled Gauntlet",
  "Radiant Kraken's Fury",
  "Radiant Last Whisper",
  "Radiant Morellonomicon",
  "Radiant Protector's Vow",
  "Radiant Quicksilver",
  "Radiant Rabadon's Deathcap",
  "Radiant Red Buff",
  "Radiant Spear of Shojin",
  "Radiant Spirit Visage",
  "Radiant Steadfast Heart",
  "Radiant Striker's Flail",
  "Radiant Sunfire Cape",
  "Radiant Thiefs Gloves",
  "Radiant Titan's Resolve",
  "Radiant Void Staff",
  "Radiant Warmog's Armor",
  "Rapid Firecannon",
  "Recurve Bow",
  "Red Buff",
  "Shadow Puppet",
  "Silvermere Dawn",
  "Slayer Emblem",
  "Sniper's Focus",
  "Sparring Gloves",
  "Spatula",
  "Spear of Shojin",
  "Spectral Cutlass",
  "Spirit Visage",
  "Statikk Shiv",
  "Steadfast Heart",
  "Striker's Flail",
  "Sunfire Cape",
  "Suspicious Trench Coat",
  "Tactician's Cape",
  "Tactician's Crown",
  "Tactician's Shield",
  "Talisman Of Ascension",
  "Tear of the Goddess",
  "The Darkin Aegis",
  "The Darkin Bow",
  "The Darkin Scythe",
  "The Darkin Staff",
  "Thief's Gloves",
  "Titan's Resolve",
  "Titanic Hydra",
  "Treasure Typhoon",
  "Trickster's Glass",
  "Unending Despair",
  "Vanquisher Emblem",
  "Void Emblem",
  "Void Gauntlet",
  "Void Staff",
  "Warden emblem",
  "Warmog's Armor",
  "Wit's End",
  "Yordle Emblem",
  "Zaun Emblem",
  "Zhonya's Paradox"
];
